title: "Counter for Beans"
theme: "just-the-docs"
color_scheme: "dark"
baseurl: "/counterbeans"
url: "https://lost-accountant.github.io"
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

search_enabled: true
